version: '3'
services:
  backend:
     build: backend/
     restart: always
     environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  frontend:
    build: frontend/
    ports:
     - "80:80"